### ISSUE TITLE
Cannot import 'config' from 'jax.config'

### ISSUE THREAD

**Issue by caoliu0706** [tianjuxue/jax-am#33]
Follow the instruction ["https://jax-am.readthedocs.io/en/latest/installation.html"](https://jax-am.readthedocs.io/en/latest/installation.html) for installation jax-am.
When run the example "python -m applications.fem.demo.example", the error occurs.

```
Traceback (most recent call last):
  File "/home/cl_linux/anaconda3/envs/jax-am/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/cl_linux/anaconda3/envs/jax-am/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/cl_linux/jax-am/applications/fem/demo/example.py", line 5, in <module>
    from jax_am.fem.models import LinearElasticity
  File "/home/cl_linux/jax-am/jax_am/fem/models.py", line 5, in <module>
    from jax_am.fem.core import FEM
  File "/home/cl_linux/jax-am/jax_am/fem/core.py", line 14, in <module>
    from jax.config import config
ImportError: cannot import name 'config' from 'jax.config' (/home/cl_linux/anaconda3/envs/jax-am/lib/python3.9/site-packages/jax/config.py)
```

**Comment by tianjuxue** [comment]
I believe this is an issue with the new JAX version. If you want to use FEM module. Please refer to [JAX-FEM](https://github.com/deepmodeling/jax-fem). We do not maintain JAX-FEM (legacy) in the JAX-AM repo.

**Comment by caoliu0706** [comment]
Thanks
